# Generated by Django 5.0.4 on 2024-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=40)),
                ('cur_unit', models.CharField(max_length=40)),
                ('ttb', models.CharField(max_length=40)),
                ('tts', models.CharField(max_length=40)),
                ('deal_bas_r', models.CharField(max_length=40)),
                ('bkpr', models.CharField(max_length=40)),
                ('yy_efee_r', models.CharField(max_length=40)),
                ('ten_dd_efee_r', models.CharField(max_length=40)),
                ('kftc_bkpr', models.CharField(max_length=40)),
                ('kftc_deal_bas_r', models.CharField(max_length=40)),
                ('cur_nm', models.CharField(max_length=40)),
            ],
        ),
    ]
